# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_sense.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 846)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_2Page1 = QtWidgets.QWidget()
        self.tabWidget_2Page1.setObjectName("tabWidget_2Page1")
        self.listWidget_2 = QtWidgets.QListWidget(self.tabWidget_2Page1)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 40, 151, 161))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 220, 151, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget_2.addTab(self.tabWidget_2Page1, "")
        self.tabWidget_2Page2 = QtWidgets.QWidget()
        self.tabWidget_2Page2.setObjectName("tabWidget_2Page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabWidget_2Page2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabWidget_2Page2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidget_2Page2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget_2.addTab(self.tabWidget_2Page2, "")
        self.gridLayout.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.sdfLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdfLineEdit.sizePolicy().hasHeightForWidth())
        self.sdfLineEdit.setSizePolicy(sizePolicy)
        self.sdfLineEdit.setObjectName("sdfLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sdfLineEdit)
        self.sdfLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sdfLabel.setObjectName("sdfLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sdfLabel)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.images_list_widget = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images_list_widget.sizePolicy().hasHeightForWidth())
        self.images_list_widget.setSizePolicy(sizePolicy)
        self.images_list_widget.setObjectName("images_list_widget")
        self.verticalLayout_4.addWidget(self.images_list_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 1, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTrain = QtWidgets.QMenu(self.menubar)
        self.menuTrain.setObjectName("menuTrain")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_project_save = QtWidgets.QAction(MainWindow)
        self.action_project_save.setObjectName("action_project_save")
        self.action_project_load = QtWidgets.QAction(MainWindow)
        self.action_project_load.setObjectName("action_project_load")
        self.action_project_add_files = QtWidgets.QAction(MainWindow)
        self.action_project_add_files.setObjectName("action_project_add_files")
        self.action_project_remove_file = QtWidgets.QAction(MainWindow)
        self.action_project_remove_file.setObjectName("action_project_remove_file")
        self.menuFile.addAction(self.action_project_load)
        self.menuFile.addAction(self.action_project_save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_project_add_files)
        self.menuFile.addAction(self.action_project_remove_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTrain.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Existed Model"))
        self.pushButton_2.setText(_translate("MainWindow", "Add New Models"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page1), _translate("MainWindow", "Automatically"))
        self.groupBox.setTitle(_translate("MainWindow", "Region Shape"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Attributes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page2), _translate("MainWindow", "Maually"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Project"))
        self.sdfLabel.setText(_translate("MainWindow", "Name: "))
        self.pushButton.setText(_translate("MainWindow", "Add Files"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove"))
        self.menuFile.setTitle(_translate("MainWindow", "Project"))
        self.menuTrain.setTitle(_translate("MainWindow", "Train"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.action_project_save.setText(_translate("MainWindow", "Save"))
        self.action_project_load.setText(_translate("MainWindow", "Load"))
        self.action_project_add_files.setText(_translate("MainWindow", "Add files"))
        self.action_project_remove_file.setText(_translate("MainWindow", "Remove file"))
