# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_sense.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 818)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.sdfLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdfLineEdit.sizePolicy().hasHeightForWidth())
        self.sdfLineEdit.setSizePolicy(sizePolicy)
        self.sdfLineEdit.setObjectName("sdfLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sdfLineEdit)
        self.sdfLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sdfLabel.setObjectName("sdfLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sdfLabel)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.list_widget_images = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_widget_images.sizePolicy().hasHeightForWidth())
        self.list_widget_images.setSizePolicy(sizePolicy)
        self.list_widget_images.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_widget_images.setObjectName("list_widget_images")
        self.verticalLayout_4.addWidget(self.list_widget_images)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.push_button_add_images = QtWidgets.QPushButton(self.groupBox_3)
        self.push_button_add_images.setObjectName("push_button_add_images")
        self.horizontalLayout_2.addWidget(self.push_button_add_images)
        self.push_button_remove_images = QtWidgets.QPushButton(self.groupBox_3)
        self.push_button_remove_images.setObjectName("push_button_remove_images")
        self.horizontalLayout_2.addWidget(self.push_button_remove_images)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(282, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_2Page1 = QtWidgets.QWidget()
        self.tabWidget_2Page1.setObjectName("tabWidget_2Page1")
        self.list_widget_models = QtWidgets.QListWidget(self.tabWidget_2Page1)
        self.list_widget_models.setGeometry(QtCore.QRect(10, 40, 151, 161))
        self.list_widget_models.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_widget_models.setObjectName("list_widget_models")
        self.label = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.label.setObjectName("label")
        self.push_button_add_models = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.push_button_add_models.setGeometry(QtCore.QRect(10, 220, 151, 25))
        self.push_button_add_models.setObjectName("push_button_add_models")
        self.push_button_remove_models = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.push_button_remove_models.setGeometry(QtCore.QRect(10, 260, 151, 25))
        self.push_button_remove_models.setObjectName("push_button_remove_models")
        self.push_button_go = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.push_button_go.setGeometry(QtCore.QRect(180, 80, 89, 25))
        self.push_button_go.setObjectName("push_button_go")
        self.tabWidget_2.addTab(self.tabWidget_2Page1, "")
        self.tabWidget_2Page2 = QtWidgets.QWidget()
        self.tabWidget_2Page2.setObjectName("tabWidget_2Page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabWidget_2Page2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidget_2Page2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_6.addWidget(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tabWidget_2Page2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tabWidget_2Page2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.tabWidget_2Page2, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.graphics_view = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics_view.sizePolicy().hasHeightForWidth())
        self.graphics_view.setSizePolicy(sizePolicy)
        self.graphics_view.setObjectName("graphics_view")
        self.verticalLayout_9.addWidget(self.graphics_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_previous_page = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_previous_page.sizePolicy().hasHeightForWidth())
        self.button_previous_page.setSizePolicy(sizePolicy)
        self.button_previous_page.setObjectName("button_previous_page")
        self.horizontalLayout.addWidget(self.button_previous_page)
        self.label_page_id = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_page_id.sizePolicy().hasHeightForWidth())
        self.label_page_id.setSizePolicy(sizePolicy)
        self.label_page_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_id.setObjectName("label_page_id")
        self.horizontalLayout.addWidget(self.label_page_id)
        self.button_next_page = QtWidgets.QPushButton(self.centralwidget)
        self.button_next_page.setObjectName("button_next_page")
        self.horizontalLayout.addWidget(self.button_next_page)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTrain = QtWidgets.QMenu(self.menubar)
        self.menuTrain.setObjectName("menuTrain")
        self.menuAnalyze = QtWidgets.QMenu(self.menubar)
        self.menuAnalyze.setObjectName("menuAnalyze")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_project_save = QtWidgets.QAction(MainWindow)
        self.action_project_save.setObjectName("action_project_save")
        self.action_project_load = QtWidgets.QAction(MainWindow)
        self.action_project_load.setObjectName("action_project_load")
        self.action_project_add_files = QtWidgets.QAction(MainWindow)
        self.action_project_add_files.setObjectName("action_project_add_files")
        self.action_project_remove_files = QtWidgets.QAction(MainWindow)
        self.action_project_remove_files.setObjectName("action_project_remove_files")
        self.action_file_zoom_in = QtWidgets.QAction(MainWindow)
        self.action_file_zoom_in.setObjectName("action_file_zoom_in")
        self.action_file_zoom_out = QtWidgets.QAction(MainWindow)
        self.action_file_zoom_out.setObjectName("action_file_zoom_out")
        self.menuFile.addAction(self.action_project_load)
        self.menuFile.addAction(self.action_project_save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_project_add_files)
        self.menuFile.addAction(self.action_project_remove_files)
        self.menuFile_2.addSeparator()
        self.menuFile_2.addAction(self.action_file_zoom_in)
        self.menuFile_2.addAction(self.action_file_zoom_out)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFile_2.menuAction())
        self.menubar.addAction(self.menuTrain.menuAction())
        self.menubar.addAction(self.menuAnalyze.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Project"))
        self.sdfLabel.setText(_translate("MainWindow", "Name: "))
        self.push_button_add_images.setText(_translate("MainWindow", "Add Images"))
        self.push_button_remove_images.setText(_translate("MainWindow", "Remove Images"))
        self.label.setText(_translate("MainWindow", "Existed Model"))
        self.push_button_add_models.setText(_translate("MainWindow", "Add Models"))
        self.push_button_remove_models.setText(_translate("MainWindow", "Remove Models"))
        self.push_button_go.setText(_translate("MainWindow", "Go"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page1), _translate("MainWindow", "Automatically"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Attributes"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton.setText(_translate("MainWindow", "Yes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page2), _translate("MainWindow", "Maually"))
        self.button_previous_page.setText(_translate("MainWindow", "Previous"))
        self.label_page_id.setText(_translate("MainWindow", "-- / --"))
        self.button_next_page.setText(_translate("MainWindow", "Next"))
        self.menuFile.setTitle(_translate("MainWindow", "Project"))
        self.menuTrain.setTitle(_translate("MainWindow", "Train"))
        self.menuAnalyze.setTitle(_translate("MainWindow", "Analyze"))
        self.menuFile_2.setTitle(_translate("MainWindow", "File"))
        self.action_project_save.setText(_translate("MainWindow", "Save"))
        self.action_project_load.setText(_translate("MainWindow", "Load"))
        self.action_project_add_files.setText(_translate("MainWindow", "Add files"))
        self.action_project_remove_files.setText(_translate("MainWindow", "Remove file"))
        self.action_file_zoom_in.setText(_translate("MainWindow", "Zoom In"))
        self.action_file_zoom_out.setText(_translate("MainWindow", "Zoom Out"))

