# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelSense.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets





class Ui_modelMainWindow(object):
    def setupUi(self, modelMainWindow):
        modelMainWindow.setObjectName("modelMainWindow")
        modelMainWindow.resize(1003, 878)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(modelMainWindow.sizePolicy().hasHeightForWidth())
        modelMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(modelMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 1, 2, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidget_2Page1 = QtWidgets.QWidget()
        self.tabWidget_2Page1.setObjectName("tabWidget_2Page1")
        self.listWidget_2 = QtWidgets.QListWidget(self.tabWidget_2Page1)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 40, 151, 161))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label = QtWidgets.QLabel(self.tabWidget_2Page1)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.tabWidget_2Page1)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 220, 151, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget_2.addTab(self.tabWidget_2Page1, "")
        self.tabWidget_2Page2 = QtWidgets.QWidget()
        self.tabWidget_2Page2.setObjectName("tabWidget_2Page2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabWidget_2Page2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tabWidget_2Page2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidget_2Page2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget_2.addTab(self.tabWidget_2Page2, "")
        self.gridLayout.addWidget(self.tabWidget_2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.sdfLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sdfLabel.setObjectName("sdfLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sdfLabel)
        self.sdfLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdfLineEdit.sizePolicy().hasHeightForWidth())
        self.sdfLineEdit.setSizePolicy(sizePolicy)
        self.sdfLineEdit.setObjectName("sdfLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sdfLineEdit)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 961, 725))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        modelMainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(modelMainWindow)
        self.statusBar.setObjectName("statusBar")
        modelMainWindow.setStatusBar(self.statusBar)


        self.retranslateUi(modelMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(modelMainWindow)

    def retranslateUi(self, modelMainWindow):
        _translate = QtCore.QCoreApplication.translate
        modelMainWindow.setWindowTitle(_translate("modelMainWindow", "Model"))
        self.label.setText(_translate("modelMainWindow", "Existed Model"))
        self.pushButton_2.setText(_translate("modelMainWindow", "Add New Models"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page1),
                                    _translate("modelMainWindow", "Automatically"))
        self.groupBox.setTitle(_translate("modelMainWindow", "Region Shape"))
        self.groupBox_2.setTitle(_translate("modelMainWindow", "Attributes"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page2),
                                    _translate("modelMainWindow", "Maually"))
        self.groupBox_3.setTitle(_translate("modelMainWindow", "Project"))
        self.sdfLabel.setText(_translate("modelMainWindow", "Name: "))
        self.pushButton.setText(_translate("modelMainWindow", "Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("modelMainWindow", "lable"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("modelMainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("modelMainWindow", "Page 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("modelMainWindow", "train"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("modelMainWindow", "analyze"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    modelMainWindow = QtWidgets.QMainWindow()
    ui = Ui_modelMainWindow()
    ui.setupUi(modelMainWindow)
    setupUi2(modelMainWindow)
    modelMainWindow.show()
    sys.exit(app.exec_())
